//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E2EDashboard.API.Core.Resources
{
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Asset {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Asset() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("E2EDashboard.Utility.Resources.Asset", typeof(Asset).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select atleast one search criteria..
        /// </summary>
        public static string V001 {
            get {
                return ResourceManager.GetString("V001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To date should be greater than From date..
        /// </summary>
        public static string V002 {
            get {
                return ResourceManager.GetString("V002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid date format..
        /// </summary>
        public static string V003 {
            get {
                return ResourceManager.GetString("V003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login user is required..
        /// </summary>
        public static string V004 {
            get {
                return ResourceManager.GetString("V004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No box found to delete with given box number : .
        /// </summary>
        public static string V005 {
            get {
                return ResourceManager.GetString("V005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Box number is required..
        /// </summary>
        public static string V006 {
            get {
                return ResourceManager.GetString("V006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District code is required..
        /// </summary>
        public static string V007 {
            get {
                return ResourceManager.GetString("V007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer ID is required..
        /// </summary>
        public static string V008 {
            get {
                return ResourceManager.GetString("V008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SKP Order number required..
        /// </summary>
        public static string V009 {
            get {
                return ResourceManager.GetString("V009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset ID is required.
        /// </summary>
        public static string V010 {
            get {
                return ResourceManager.GetString("V010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset assignment date is required..
        /// </summary>
        public static string V011 {
            get {
                return ResourceManager.GetString("V011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project ID is required..
        /// </summary>
        public static string V012 {
            get {
                return ResourceManager.GetString("V012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected completion date is required..
        /// </summary>
        public static string V013 {
            get {
                return ResourceManager.GetString("V013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset ID should not be &apos;0&apos;..
        /// </summary>
        public static string V014 {
            get {
                return ResourceManager.GetString("V014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project ID should not be &apos;0&apos;..
        /// </summary>
        public static string V015 {
            get {
                return ResourceManager.GetString("V015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Box status should not be &apos;0&apos;..
        /// </summary>
        public static string V016 {
            get {
                return ResourceManager.GetString("V016", resourceCulture);
            }
        }
    }
}
